steps:
    - name: slack-begin
      image: plugins/slack
      settings:
          webhook:
              from_secret: slack_webhook_url
          username: Woodpecker
          template: |
              {{repo.name}}/{{build.branch}} - Started #{{build.number}} 
              URL: <{{build.link}}|Open>
    - name: build
      secrets: [vault_master_ssh_priv_key, vault_master_ssh_pub_key]
      image: docker
      environment:
          - branch={{build.branch}}
      commands:
          - echo test
          - /bin/sh build.sh
    - name: slack-end
      image: plugins/slack
      settings:
          webhook:
              from_secret: slack_webhook_url
          username: Woodpecker
          template: |
              {{repo.name}}/{{build.branch}} - Finished #{{build.number}}
              URL: <{{build.link}}|Open>
    - name: slack-failure
      image: plugins/slack
      settings:
          webhook:
              from_secret: slack_webhook_url
          username: Woodpecker
          template: |
              {{repo.name}}/{{build.branch}} - Failure #{{build.number}}
              URL: <{{build.link}}|Open>
      when:
          status:
              - failure
