steps:
    # - name: slack-begin
    #   image: plugins/slack
    #   secrets: [slack_webhook_url]
    #   settings:
    #       webhook: $SLACK_WEBHOOK_URL
    #       username: Drone
    #       template: >
    #           {{repo.name}}/{{build.branch}} - Started #{{build.number}} (<{{build.link}}>|Open)
    - name: build
      secrets: [vault_master_ssh_priv_key, vault_master_ssh_pub_key]
      image: docker
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock
      commands:
          - cd deploy && /bin/bash build.sh
    # - name: slack-end
    #   image: plugins/slack
    #   settings:
    #       webhook: $SLACK_WEBHOOK_URL
    #       username: Drone
    #       template: >
    #           {{repo.name}}/{{build.branch}} - Finished #{{build.number}} (<{{build.link}}>|Open)

    #   secrets: [slack_webhook_url]
