steps:
    - name: init
      image: ubuntu
      commands:
          - echo "$VAULT_MASTER_SSH_PUB_KEY"
          - echo "$VAULT_MASTER_SSH_PRIV_KEY"
          - echo "$SLACK_WEBHOOK_URL"
      secrets: [vault_master_ssh_pub_key, vault_master_ssh_priv_key, slack_webhook_url]
      # - name: slack-begin
      #   image: plugins/slack
      #   settings:
      #     webhook:
      #       from_secret: SLACK_WEBHOOK_URL
      #   username: Drone
      #   template:
      #     {{repo.name}}/{{build.branch}} - Started #{{build.number}} (<{{build.link}}>|Open)
      # - name: build
      #   settings:
      #     VAULT_MASTER_SSH_PRIV_KEY:
      #       from_secret: VAULT_MASTER_SSH_PRIV_KEY
      #     VAULT_MASTER_SSH_PUB_KEY:
      #       from_secret: VAULT_MASTER_SSH_PUB_KEY
      #   image: devforth/drone-builder
      #   commands:
      #     - cd deploy && /bin/bash build.sh
      # - name: slack-end
      #   image: plugins/slack
      #   settings:
      #     webhook:
      #       from_secret: SLACK_WEBHOOK_URL
      #   username: Drone
      #   template:
      #     {{repo.name}}/{{build.branch}} - Finished #{{build.number}} (<{{build.link}}>|Open)
