version: '3.9'

services:
  db:
    container_name: neuro_db
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${DATABASE_PORT}:5432"
    env_file:
      - .env
    networks:
      - labnet
    volumes:
      - neuro_postgres_db:/var/lib/postgresql/data
    restart: always

  backend:
    container_name: neuro_backend
    build: ./backend
    environment:
      - DATABASE_PORT=5432
      - DATABASE_HOST=db
    env_file:
      - .env
    networks:
      - labnet
    ports:
      - 3000:3000
    depends_on:
      - db
    restart: always

volumes:
  neuro_postgres_db:
    driver: local
networks:
  labnet:
