version: '3.9'

services:
  db:
    container_name: neuro_db
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${DATABASE_PORT}:5432"
    env_file:
      - .env
    networks:
      - labnet
    volumes:
      - neuro_postgres_db:/var/lib/postgresql/data
    restart: always

  redis:
    container_name: neuro_redis
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - labnet

  backend:
    container_name: neuro_backend
    build: ./backend
    environment:
      - DATABASE_PORT=5432
      - DATABASE_HOST=db
      - REDIS_HOST=redis
    env_file:
      - .env
    networks:
      - labnet
    ports:
      - 4000:4000
    depends_on:
      - db
    restart: always

  bot:
    container_name: neuro_bot
    build: ./neuro-reply-bot-reworked
    environment:
      - API_URL=http://backend:3000
      - TZ=Europe/Moscow
      - REDIS_HOST=redis
    networks:
      - labnet
    depends_on:
      - backend
      - redis
    restart: always

volumes:
  neuro_postgres_db:
    driver: local
  redis_data:
networks:
  labnet:
