version: '3.9'

services:
  db:
    container_name: neuro_db
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${DATABASE_PORT}:5432"
    env_file:
      - .env
    networks:
      - labnet
    volumes:
      - neuro_postgres_db:/var/lib/postgresql/data
    restart: always
  backend:
    container_name: neuro_backend
    build: ./backend
    stdin_open: true
    environment:
      - DATABASE_HOST='db'
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_DB=${DATABASE_NAME}
    networks:
      - labnet
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  neuro_postgres_db:
    driver: local
networks:
  labnet: {}