name: Aboba

on:
  push:
    branches: [test]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: catthehacker/ubuntu:act-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Set up Docker BuildX
          uses: docker/setup-buildx-action@v3

        - name: Build the Docker image
          uses: isbang/compose-action@v1.5.1
          with: 
            compose_file: "./docker-compose.yml"
