name: Aboba

on:
    push:
        branches: [test]

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: catthehacker/ubuntu:act-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build the Docker image
              run: docker-compose up -d
